POST http://localhost:3333/videos
Content-Type: application/json

{
  "title":  "Vídeo node",
  "description":  "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/181976ee-b148-44cf-bc49-16aa9568325a
Content-Type: application/json

{
  "title":  "Vídeo 02",
  "description":  "Esse é o segundo vídeo",
  "duration": 180
}

### 
DELETE http://localhost:3333/videos/181976ee-b148-44cf-bc49-16aa9568325a